namespace SmartCon.Core.Services;

public static partial class LocalizationService
{
    private static void AddFamilyManagerKeys(Dictionary<string, string> ru, Dictionary<string, string> en)
    {
        ru["FM_SearchPlaceholder"] = "Поиск по имени или тегу..."; en["FM_SearchPlaceholder"] = "Search by name or tag...";
        ru["FM_Import"] = "Импорт"; en["FM_Import"] = "Import";
        ru["FM_ImportFile"] = "Импорт файла"; en["FM_ImportFile"] = "Import File";
        ru["FM_ImportFolder"] = "Импорт папки"; en["FM_ImportFolder"] = "Import Folder";
        ru["FM_LoadToProject"] = "Загрузить в проект"; en["FM_LoadToProject"] = "Load to Project";
        ru["FM_LoadAndPlace"] = "Загрузить и разместить"; en["FM_LoadAndPlace"] = "Load and Place";
        ru["FM_Loading"] = "Загрузка {0}..."; en["FM_Loading"] = "Loading {0}...";
        ru["FM_ExtractTypes"] = "Извлечь типоразмеры"; en["FM_ExtractTypes"] = "Extract Types";
        ru["FM_ImportData"] = "Импорт данных"; en["FM_ImportData"] = "Import Data";
        ru["FM_PlaceType"] = "Разместить тип"; en["FM_PlaceType"] = "Place Type";
        ru["FM_Edit"] = "Редактировать"; en["FM_Edit"] = "Edit";
        ru["FM_ImportActiveFile"] = "Импорт активного файла"; en["FM_ImportActiveFile"] = "Import Active File";
        ru["FM_ActiveDocNotFamily"] = "Активный документ не является семейством"; en["FM_ActiveDocNotFamily"] = "Active document is not a family";
        ru["FM_ImportSystemFamily"] = "Импорт системного семейства"; en["FM_ImportSystemFamily"] = "Import System Family";
        ru["FM_ImportSelectedElements"] = "Импорт выделенных элементов"; en["FM_ImportSelectedElements"] = "Import Selected Elements";
        ru["FM_SelectElementsPrompt"] = "Выберите элементы в Revit (системные или загружаемые семейства)..."; en["FM_SelectElementsPrompt"] = "Select elements in Revit (system or loadable families)...";
        ru["FM_ImportActiveConfirmTitle"] = "Импорт активного файла"; en["FM_ImportActiveConfirmTitle"] = "Import Active File";
        ru["FM_ImportActiveConfirmMessage"] = "Импортировать в каталог: {0} системных категорий ({1} типов) и {2} загружаемых семейств?"; en["FM_ImportActiveConfirmMessage"] = "Import to catalog: {0} system categories ({1} types) and {2} loadable families?";
        ru["FM_ActiveDocNotProject"] = "Активный документ не является проектом. Откройте проект Revit."; en["FM_ActiveDocNotProject"] = "Active document is not a project. Open a Revit project.";
        ru["FM_SystemFamilySelectPrompt"] = "Выберите элементы системного семейства в Revit..."; en["FM_SystemFamilySelectPrompt"] = "Select system family elements in Revit...";
        ru["FM_SystemFamilyImported"] = "Импортировано системных типов: {0}"; en["FM_SystemFamilyImported"] = "System types imported: {0}";
        ru["FM_SystemFamilyImportFailed"] = "Ошибка импорта системного семейства"; en["FM_SystemFamilyImportFailed"] = "System family import failed";
        ru["FM_SystemFamilyPreparing"] = "Подготовлено {0} категорий, импорт..."; en["FM_SystemFamilyPreparing"] = "Prepared {0} categories, importing...";
        ru["FM_EditSystemFamily"] = "Редактировать системное семейство"; en["FM_EditSystemFamily"] = "Edit System Family";
        ru["FM_NoSystemFamiliesFound"] = "В проекте не найдено размещённых системных семейств"; en["FM_NoSystemFamiliesFound"] = "No placed system families found in the project";
        ru["FM_EditMetadata"] = "Редактировать"; en["FM_EditMetadata"] = "Edit";
        ru["FM_NoActiveDocument"] = "Нет активного документа"; en["FM_NoActiveDocument"] = "No active document";
        ru["FM_ImportProgress"] = "Импорт {0} из {1}..."; en["FM_ImportProgress"] = "Importing {0} of {1}...";
        ru["FM_ColName"] = "Имя"; en["FM_ColName"] = "Name";
        ru["FM_ColStatus"] = "Статус"; en["FM_ColStatus"] = "Status";
        ru["FM_ColVersion"] = "Версия"; en["FM_ColVersion"] = "Version";
        ru["FM_ColUpdated"] = "Обновлено"; en["FM_ColUpdated"] = "Updated";
        ru["FM_Save"] = "Сохранить"; en["FM_Save"] = "Save";
        ru["FM_Cancel"] = "Отмена"; en["FM_Cancel"] = "Cancel";
        ru["FM_Name"] = "Имя"; en["FM_Name"] = "Name";
        ru["FM_Description"] = "Описание"; en["FM_Description"] = "Description";
        ru["FM_Category"] = "Категория"; en["FM_Category"] = "Category";
        ru["FM_Tags"] = "Теги"; en["FM_Tags"] = "Tags";
        ru["FM_Status"] = "Статус"; en["FM_Status"] = "Status";
        ru["FM_Status_Active"] = "Актуальное"; en["FM_Status_Active"] = "Current";
        ru["FM_Status_Deprecated"] = "Неактуальное"; en["FM_Status_Deprecated"] = "Deprecated";
        ru["FM_ImportSuccess"] = "Импортировано: {0}"; en["FM_ImportSuccess"] = "Imported: {0}";
        ru["FM_ImportError"] = "Ошибка импорта: {0}"; en["FM_ImportError"] = "Import error: {0}";
        ru["FM_ImportPrepareError"] = "Ошибка подготовки"; en["FM_ImportPrepareError"] = "Preparation error";
        ru["FM_ImportResultFormat"] = "Импортировано: {0}, пропущено: {1}, ошибок: {2} / {3}"; en["FM_ImportResultFormat"] = "Imported: {0}, skipped: {1}, errors: {2} / {3}";
        ru["FM_ImportStatusImport"] = "Импорт: {0}/{1}"; en["FM_ImportStatusImport"] = "Import: {0}/{1}";
        ru["FM_ImportStatusSkipped"] = "Пропущено: {0}"; en["FM_ImportStatusSkipped"] = "Skipped: {0}";
        ru["FM_ImportStatusSkippedIdentical"] = " (идентично)"; en["FM_ImportStatusSkippedIdentical"] = " (identical)";
        ru["FM_ImportStatusErrors"] = "Ошибок: {0}"; en["FM_ImportStatusErrors"] = "Errors: {0}";
        ru["FM_ImportCompleted"] = "Импорт {0}/{1} семейств завершён"; en["FM_ImportCompleted"] = "Import of {0}/{1} families completed";
        ru["FM_FamilyFileNotFound"] = "Файл семейства не найден"; en["FM_FamilyFileNotFound"] = "Family file not found";
        ru["FM_ImportDataResultFormat"] = "Импортировано: {0} типоразмеров, {1} значений найдено"; en["FM_ImportDataResultFormat"] = "Imported: {0} types, {1} values found";
        ru["FM_ImportDataError"] = "Ошибка импорта: {0}"; en["FM_ImportDataError"] = "Import error: {0}";
        ru["FM_ImportToCategory"] = "Импорт в категорию"; en["FM_ImportToCategory"] = "Import to category";
        ru["FM_ImportDataProgress"] = "Обработка {0} из {1}: {2}"; en["FM_ImportDataProgress"] = "Processing {0} of {1}: {2}";
        ru["FM_NoFamiliesInCategory"] = "В категории нет семейств"; en["FM_NoFamiliesInCategory"] = "No families in category";
        ru["FM_LoadSuccess"] = "Семейство \"{0}\" загружено в проект"; en["FM_LoadSuccess"] = "Family \"{0}\" loaded into project";
        ru["FM_LoadAndPlaceSuccess"] = "Семейство \"{0}\" — нажмите для размещения"; en["FM_LoadAndPlaceSuccess"] = "Family \"{0}\" — click to place";
        ru["FM_LoadError"] = "Ошибка загрузки: {0}"; en["FM_LoadError"] = "Load error: {0}";
        ru["FM_DuplicateSkipped"] = "Дубликат пропущен: {0}"; en["FM_DuplicateSkipped"] = "Duplicate skipped: {0}";
        ru["FM_DbSwitched"] = "База данных переключена на: {0}"; en["FM_DbSwitched"] = "Database switched to: {0}";
        ru["FM_DbSwitchError"] = "Ошибка переключения базы данных"; en["FM_DbSwitchError"] = "Error switching database";
        ru["FM_DbCreated"] = "База данных \"{0}\" создана"; en["FM_DbCreated"] = "Database \"{0}\" created";
        ru["FM_DbCreateError"] = "Ошибка создания БД: {0}"; en["FM_DbCreateError"] = "Error creating database: {0}";
        ru["FM_DbCreateErrorTitle"] = "Ошибка создания базы данных"; en["FM_DbCreateErrorTitle"] = "Database creation error";
        ru["FM_DbConnectError"] = "Ошибка подключения к БД: {0}"; en["FM_DbConnectError"] = "Database connection error: {0}";
        ru["FM_DbConnectErrorTitle"] = "Ошибка подключения к базе данных"; en["FM_DbConnectErrorTitle"] = "Database connection error";
        ru["FM_DbNotFoundAtPath"] = "В выбранной папке не найден файл catalog.db. Укажите корректную папку существующей БД SmartCon."; en["FM_DbNotFoundAtPath"] = "The selected folder does not contain catalog.db. Please select a valid SmartCon database folder.";
        ru["FM_DbDeleted"] = "База данных \"{0}\" удалена"; en["FM_DbDeleted"] = "Database \"{0}\" deleted";
        ru["FM_DbDeleteError"] = "Ошибка удаления БД: {0}"; en["FM_DbDeleteError"] = "Error deleting database: {0}";
        ru["FM_EmptyState_NoDatabaseTitle"] = "Нет подключённых баз данных"; en["FM_EmptyState_NoDatabaseTitle"] = "No databases connected";
        ru["FM_EmptyState_NoDatabaseHint"] = "Создайте новую базу или подключите существующую — кнопка «+» рядом со списком баз."; en["FM_EmptyState_NoDatabaseHint"] = "Create a new database or connect an existing one — use the '+' button next to the database list.";
        ru["FM_ConnectionsEmpty"] = "Нет баз данных"; en["FM_ConnectionsEmpty"] = "No databases";
        ru["FM_DbDeleteTitle"] = "Удаление базы данных"; en["FM_DbDeleteTitle"] = "Delete Database";
        ru["FM_DbDeletePrompt"] = "Введите \"{0}\" для подтверждения удаления:"; en["FM_DbDeletePrompt"] = "Enter \"{0}\" to confirm deletion:";
        ru["FM_DbDeleteFilesLocked"] = "БД \"{0}\" удалена из списка, но файлы не удалены, так как используются в проекте. Закройте Revit, чтобы удалить остатки."; en["FM_DbDeleteFilesLocked"] = "Database \"{0}\" removed from the list, but files could not be deleted because they are in use by the project. Close Revit to remove remaining files.";
        ru["FM_DbNewTitle"] = "Новая база данных"; en["FM_DbNewTitle"] = "New Database";
        ru["FM_DbNewPrompt"] = "Введите название новой базы данных:"; en["FM_DbNewPrompt"] = "Enter new database name:";
        ru["FM_DbNewPlaceholder"] = "Название базы данных"; en["FM_DbNewPlaceholder"] = "Database name";
        ru["FM_FamilyDeleted"] = "Семейство \"{0}\" удалено из каталога"; en["FM_FamilyDeleted"] = "Family \"{0}\" deleted from catalog";
        ru["FM_FamilyDeleteError"] = "Ошибка удаления семейства"; en["FM_FamilyDeleteError"] = "Error deleting family";
        ru["FM_FamilyDeleteTitle"] = "Удаление семейства"; en["FM_FamilyDeleteTitle"] = "Delete Family";
        ru["FM_FamilyDeletePrompt"] = "Удалить семейство \"{0}\" из каталога?"; en["FM_FamilyDeletePrompt"] = "Delete family \"{0}\" from catalog?";
        ru["FM_DeleteFromCatalog"] = "Удалить из каталога"; en["FM_DeleteFromCatalog"] = "Delete from catalog";
        ru["FM_NoVersionSelected"] = "Версия не выбрана"; en["FM_NoVersionSelected"] = "No version selected";
        ru["FM_NoCategory"] = "Без категории"; en["FM_NoCategory"] = "No category";
        ru["FM_DbSelectPath"] = "Выберите расположение базы данных"; en["FM_DbSelectPath"] = "Select database location";
        ru["FM_Disconnect"] = "Отключить базу данных"; en["FM_Disconnect"] = "Disconnect database";

        ru["FM_Update"] = "Обновить"; en["FM_Update"] = "Update";
        ru["FM_UpdateKeepParams"] = "Сохранить параметры"; en["FM_UpdateKeepParams"] = "Keep instance parameters";
        ru["FM_UpdateOverwriteParams"] = "Перезаписать параметры"; en["FM_UpdateOverwriteParams"] = "Overwrite parameters";
        ru["FM_UpdateBatchAllStale"] = "Пакетное обновление всех устаревших"; en["FM_UpdateBatchAllStale"] = "Batch update all stale";
        ru["FM_Check"] = "Проверить"; en["FM_Check"] = "Check";
        ru["FM_Stale"] = "Устарело"; en["FM_Stale"] = "Stale";
        ru["FM_StaleTooltipNone"] = "Актуальная версия"; en["FM_StaleTooltipNone"] = "Up to date";
        ru["FM_StaleTooltipNoES"] = "Нет маркера версии (загружено до 2.0)"; en["FM_StaleTooltipNoES"] = "No version marker (loaded before 2.0)";
        ru["FM_StaleTooltipMismatch"] = "Версия в проекте отличается от каталога"; en["FM_StaleTooltipMismatch"] = "Project version differs from catalog";
        ru["FM_StaleTooltipRevitVer"] = "Загружено в другой версии Revit"; en["FM_StaleTooltipRevitVer"] = "Loaded in a different Revit version";
        ru["FM_StaleTooltipNotInCatalog"] = "Семейство не найдено в каталоге FM"; en["FM_StaleTooltipNotInCatalog"] = "Family not found in FM catalog";
        ru["FM_StaleCheckInProgress"] = "Проверка…"; en["FM_StaleCheckInProgress"] = "Checking…";
        ru["FM_StaleUpdateInProgress"] = "Обновление…"; en["FM_StaleUpdateInProgress"] = "Updating…";
        ru["FM_StaleCategoryTooltipOne"] = "1 устаревшее семейство"; en["FM_StaleCategoryTooltipOne"] = "1 stale family";
        ru["FM_StaleCategoryTooltipMany"] = "{0} устаревших семейств"; en["FM_StaleCategoryTooltipMany"] = "{0} stale families";
        ru["FM_UnavailableTooltipDeprecated"] = "Неактуальное семейство — загрузка в проект запрещена. Вернуть в работу: Свойства → Статус «Актуальное»."; en["FM_UnavailableTooltipDeprecated"] = "Family is deprecated — loading into the project is not allowed. To restore: Properties → Status 'Current'.";
        ru["FM_UnavailableTooltipDeprecatedShort"] = "Неактуальное семейство — загрузка в проект запрещена."; en["FM_UnavailableTooltipDeprecatedShort"] = "Family is deprecated — loading into the project is not allowed.";
        ru["FM_UnavailableTooltipRevitFix"] = "Сохранено в Revit {0} — нельзя загрузить в Revit {1}. Сделайте активной совместимую версию: Свойства → Версии."; en["FM_UnavailableTooltipRevitFix"] = "Saved in Revit {0} — cannot be loaded into Revit {1}. Make a compatible version active: Properties → Versions.";
        ru["FM_UnavailableTooltipRevitNone"] = "Сохранено в Revit {0} — нельзя загрузить в Revit {1}. В каталоге нет версии, совместимой с Revit {1}."; en["FM_UnavailableTooltipRevitNone"] = "Saved in Revit {0} — cannot be loaded into Revit {1}. The catalog has no version compatible with Revit {1}.";
        ru["FM_UpdateSuccess"] = "Обновлено: {0} → {1}"; en["FM_UpdateSuccess"] = "Updated: {0} → {1}";
        ru["FM_UpdateIdentical"] = "Файл идентичен текущей версии: {0}"; en["FM_UpdateIdentical"] = "File is identical to current version: {0}";
        ru["FM_UpdateIdenticalCurrent"] = "Этот файл уже является текущей версией семейства"; en["FM_UpdateIdenticalCurrent"] = "This file is already the current version of this family";
        ru["FM_UpdateError"] = "Ошибка обновления: {0}"; en["FM_UpdateError"] = "Update error: {0}";
        ru["FM_Refresh"] = "Обновить"; en["FM_Refresh"] = "Refresh";
        ru["FM_RefreshTooltip"] = "Обновить дерево категорий"; en["FM_RefreshTooltip"] = "Refresh category tree";
        ru["FM_ClearSearch"] = "Очистить"; en["FM_ClearSearch"] = "Clear";
        ru["FM_Refreshed"] = "Обновлено"; en["FM_Refreshed"] = "Refreshed";

        ru["FM_CTE_Title"] = "Редактор дерева категорий"; en["FM_CTE_Title"] = "Category Tree Editor";
        ru["FM_CTE_AddRoot"] = "+ Корень"; en["FM_CTE_AddRoot"] = "+ Root";
        ru["FM_CTE_AddChild"] = "+ Вложенная"; en["FM_CTE_AddChild"] = "+ Child";
        ru["FM_CTE_Rename"] = "Переименовать"; en["FM_CTE_Rename"] = "Rename";
        ru["FM_CTE_Delete"] = "Удалить"; en["FM_CTE_Delete"] = "Delete";
        ru["FM_CTE_Import"] = "Импорт"; en["FM_CTE_Import"] = "Import";
        ru["FM_CTE_Export"] = "Экспорт"; en["FM_CTE_Export"] = "Export";
        ru["FM_CTE_Close"] = "Закрыть"; en["FM_CTE_Close"] = "Close";
        ru["FM_CTE_AddCategory"] = "Добавить категорию"; en["FM_CTE_AddCategory"] = "Add Category";
        ru["FM_CTE_CategoryName"] = "Название категории:"; en["FM_CTE_CategoryName"] = "Category name:";
        ru["FM_CTE_AddSubcategory"] = "Добавить подкатегорию"; en["FM_CTE_AddSubcategory"] = "Add Subcategory";
        ru["FM_CTE_SubcategoryName"] = "Название подкатегории:"; en["FM_CTE_SubcategoryName"] = "Subcategory name:";
        ru["FM_CTE_NewName"] = "Новое название:"; en["FM_CTE_NewName"] = "New name:";
        ru["FM_CTE_DeleteCategory"] = "Удаление категории"; en["FM_CTE_DeleteCategory"] = "Delete Category";
        ru["FM_CTE_DeleteConfirm"] = "Удалить \"{0}\"? {1} семейств будут перемещены в \"{2}\"."; en["FM_CTE_DeleteConfirm"] = "Delete \"{0}\"? {1} families will be moved to \"{2}\".";
        ru["FM_CTE_DeleteEmpty"] = "Удалить \"{0}\"?"; en["FM_CTE_DeleteEmpty"] = "Delete \"{0}\"?";
        ru["FM_CTE_Deleted"] = "Удалено: {0}"; en["FM_CTE_Deleted"] = "Deleted: {0}";
        ru["FM_CTE_Saved"] = "Сохранено"; en["FM_CTE_Saved"] = "Saved";
        ru["FM_CTE_ImportTree"] = "Импорт дерева категорий"; en["FM_CTE_ImportTree"] = "Import Category Tree";
        ru["FM_CTE_Imported"] = "Импортировано {0} категорий"; en["FM_CTE_Imported"] = "Imported {0} categories";
        ru["FM_CTE_ExportTree"] = "Экспорт дерева категорий"; en["FM_CTE_ExportTree"] = "Export Category Tree";
        ru["FM_CTE_Exported"] = "Экспортировано в {0}"; en["FM_CTE_Exported"] = "Exported to {0}";
        ru["FM_CTE_AttrExists"] = "Атрибут \"{0}\" уже существует."; en["FM_CTE_AttrExists"] = "Attribute \"{0}\" already exists.";
        ru["FM_CTE_ExportAttrs"] = "Экспорт атрибутов"; en["FM_CTE_ExportAttrs"] = "Export Attributes";
        ru["FM_CTE_ExportFull"] = "Экспорт полного пакета"; en["FM_CTE_ExportFull"] = "Export Full Package";
        ru["FM_CTE_CategoriesAndAttrs"] = "Категории и атрибуты"; en["FM_CTE_CategoriesAndAttrs"] = "Categories & Attributes";
        ru["FM_CTE_CategoryTree"] = "Дерево категорий"; en["FM_CTE_CategoryTree"] = "Category Tree";
        ru["FM_CTE_AttributesFor"] = "Атрибуты:"; en["FM_CTE_AttributesFor"] = "Attributes:";
        ru["FM_CTE_SelectCategory"] = "Выберите категорию"; en["FM_CTE_SelectCategory"] = "Select a category";
        ru["FM_CTE_SelectCategoryHint"] = "Выберите категорию для управления атрибутами"; en["FM_CTE_SelectCategoryHint"] = "Select a category to manage attributes";
        ru["FM_CTE_AllGroups"] = "Все атрибуты"; en["FM_CTE_AllGroups"] = "All attributes";
        ru["FM_CTE_SearchAttrs"] = "Поиск атрибутов..."; en["FM_CTE_SearchAttrs"] = "Search attributes...";
        ru["FM_CTE_Inherited"] = "(наследован)"; en["FM_CTE_Inherited"] = "(inherited)";
        ru["FM_CTE_NewAttrName"] = "Новый атрибут"; en["FM_CTE_NewAttrName"] = "New attribute";
        ru["FM_CTE_AddAttr"] = "Добавить"; en["FM_CTE_AddAttr"] = "Add";
        ru["FM_CTE_AttrLibrary"] = "Библиотека атрибутов..."; en["FM_CTE_AttrLibrary"] = "Attribute Library...";
        ru["FM_CTE_ImportJson"] = "Импорт из JSON"; en["FM_CTE_ImportJson"] = "Import JSON";
        ru["FM_CTE_UnsavedChangesTitle"] = "Несохранённые изменения"; en["FM_CTE_UnsavedChangesTitle"] = "Unsaved Changes";
        ru["FM_CTE_UnsavedChangesMessage"] = "У вас есть несохранённые изменения. Сохранить перед закрытием?"; en["FM_CTE_UnsavedChangesMessage"] = "You have unsaved changes. Save before closing?";
        ru["FM_CTE_ExportColon"] = "Экспорт:"; en["FM_CTE_ExportColon"] = "Export:";
        ru["FM_CTE_ContextMenu_Rename"] = "Переименовать"; en["FM_CTE_ContextMenu_Rename"] = "Rename";
        ru["FM_CTE_ContextMenu_AddChild"] = "Добавить подкатегорию"; en["FM_CTE_ContextMenu_AddChild"] = "Add Subcategory";
        ru["FM_CTE_ContextMenu_Delete"] = "Удалить"; en["FM_CTE_ContextMenu_Delete"] = "Delete";
        ru["FM_CTE_NewCategory"] = "Новая категория"; en["FM_CTE_NewCategory"] = "New Category";
        ru["FM_CTE_Attributes"] = "Атрибуты"; en["FM_CTE_Attributes"] = "Attributes";

        ru["FM_CP_Title"] = "Выбор категории"; en["FM_CP_Title"] = "Select Category";
        ru["FM_CP_Clear"] = "Сбросить"; en["FM_CP_Clear"] = "Clear";

        ru["FM_Tip_CreateDb"] = "Создать новую базу данных"; en["FM_Tip_CreateDb"] = "Create new database";
        ru["FM_Tip_ConnectDb"] = "Подключить существующую базу данных"; en["FM_Tip_ConnectDb"] = "Connect existing database";
        ru["FM_Tip_EditCategories"] = "Редактировать категории"; en["FM_Tip_EditCategories"] = "Edit categories";

        ru["FM_Properties"] = "Свойства"; en["FM_Properties"] = "Properties";
        ru["FM_Props_SelectImage"] = "Выберите изображение"; en["FM_Props_SelectImage"] = "Select image";
        ru["FM_Props_AddFile"] = "Выберите файл"; en["FM_Props_AddFile"] = "Select file";
        ru["FM_Tab_General"] = "Общие"; en["FM_Tab_General"] = "General";
        ru["FM_Tab_Content"] = "Контент"; en["FM_Tab_Content"] = "Content";
        ru["FM_Tab_Attributes"] = "Атрибуты"; en["FM_Tab_Attributes"] = "Attributes";
        ru["FM_Tab_3DView"] = "3D Просмотр"; en["FM_Tab_3DView"] = "3D Preview";
        ru["FM_Tab_Versions"] = "Версии"; en["FM_Tab_Versions"] = "Versions";
        ru["FM_Version_Column_Version"] = "Версия"; en["FM_Version_Column_Version"] = "Version";
        ru["FM_Version_Column_FileName"] = "Имя семейства"; en["FM_Version_Column_FileName"] = "Family name";
        ru["FM_Version_Column_Revit"] = "Revit"; en["FM_Version_Column_Revit"] = "Revit";
        ru["FM_Version_Column_Date"] = "Дата"; en["FM_Version_Column_Date"] = "Date";
        ru["FM_Version_Column_Author"] = "Автор"; en["FM_Version_Column_Author"] = "Author";
        ru["FM_Version_Column_Types"] = "Типы"; en["FM_Version_Column_Types"] = "Types";
        ru["FM_Version_Column_Active"] = "Статус"; en["FM_Version_Column_Active"] = "Status";
        ru["FM_ActiveBadge"] = "Активная"; en["FM_ActiveBadge"] = "Active";
        ru["FM_MakeActive"] = "Сделать активной"; en["FM_MakeActive"] = "Make Active";
        ru["FM_MakeActive_Tooltip"] = "Сделать эту версию активной для всех операций каталога (загрузка в проект, stale detection)"; en["FM_MakeActive_Tooltip"] = "Make this version active for all catalog operations (Load to Project, Stale Detection)";
        ru["FM_DeleteVersion"] = "Удалить"; en["FM_DeleteVersion"] = "Delete";
        ru["FM_DeleteVersion_Tooltip"] = "Полностью удалить версию из каталога вместе с файлами и атрибутами"; en["FM_DeleteVersion_Tooltip"] = "Completely remove version from catalog with all its files and attributes";
        ru["FM_Confirm_MakeActive_Title"] = "Смена активной версии"; en["FM_Confirm_MakeActive_Title"] = "Change Active Version";
        ru["FM_Confirm_MakeActive_Body"] = "Сделать версию {0} активной вместо {1}? Все последующие операции (загрузка в проект, проверка устаревания, перезапись) будут идти через версию {0}."; en["FM_Confirm_MakeActive_Body"] = "Make version {0} active instead of {1}? All subsequent operations (Load to Project, stale check, overwrite) will go through version {0}.";
        ru["FM_Confirm_DeleteVersion_Title"] = "Удаление версии"; en["FM_Confirm_DeleteVersion_Title"] = "Delete Version";
        ru["FM_Confirm_DeleteVersion_Body"] = "Удалить версию {0} семейства «{1}»? Это действие необратимо. Версия будет полностью удалена из каталога вместе с файлами, типами и атрибутами."; en["FM_Confirm_DeleteVersion_Body"] = "Delete version {0} of family \"{1}\"? This action is irreversible. The version will be completely removed from the catalog along with files, types, and attributes.";
        ru["FM_Error_CannotDeleteActive"] = "Нельзя удалить активную версию. Сначала переключитесь на другую версию."; en["FM_Error_CannotDeleteActive"] = "Cannot delete the active version. Switch to another version first.";
        ru["FM_Warn_FilesNotDeleted_Title"] = "Файлы не удалены"; en["FM_Warn_FilesNotDeleted_Title"] = "Files not deleted";
        ru["FM_Warn_FilesNotDeleted_Body"] = "Версия удалена из базы, но файлы на диске остались (вероятно, заблокированы Revit или другим процессом). Путь: {0}"; en["FM_Warn_FilesNotDeleted_Body"] = "Version was deleted from the database but some files remain on disk (likely locked by Revit or another process). Path: {0}";
        ru["FM_BatchImport_MakeActive"] = "Сделать активной"; en["FM_BatchImport_MakeActive"] = "Make Active";
        ru["FM_Props_Version"] = "Версия"; en["FM_Props_Version"] = "Version";
        ru["FM_Props_RevitCategory"] = "Категория Revit"; en["FM_Props_RevitCategory"] = "Revit Category";
        ru["FM_Fact_PartType"] = "Тип детали"; en["FM_Fact_PartType"] = "Part Type";
        ru["FM_Props_Created"] = "Создано"; en["FM_Props_Created"] = "Created";
        ru["FM_Props_Updated"] = "Обновлено"; en["FM_Props_Updated"] = "Updated";
        ru["FM_Props_NoAvatar"] = "Нет изображения"; en["FM_Props_NoAvatar"] = "No image";
        ru["FM_Tooltip_NoImage"] = "Нет изображения"; en["FM_Tooltip_NoImage"] = "No image";
        ru["FM_Tooltip_NoDescription"] = "Нет описания"; en["FM_Tooltip_NoDescription"] = "No description";
        ru["FM_Tooltip_Loading"] = "Загрузка..."; en["FM_Tooltip_Loading"] = "Loading...";
        ru["FM_Props_ChangeImage"] = "Сменить"; en["FM_Props_ChangeImage"] = "Change";
        ru["FM_Props_RemoveImage"] = "Удалить"; en["FM_Props_RemoveImage"] = "Remove";
        ru["FM_Props_Images"] = "Изображения"; en["FM_Props_Images"] = "Images";
        ru["FM_Props_Videos"] = "Видео"; en["FM_Props_Videos"] = "Videos";
        ru["FM_Props_Documents"] = "Документы"; en["FM_Props_Documents"] = "Documents";
        ru["FM_Props_LookupTables"] = "Таблицы поиска (CSV)"; en["FM_Props_LookupTables"] = "Lookup Tables (CSV)";
        ru["FM_Props_Spreadsheets"] = "Электронные таблицы (XLS)"; en["FM_Props_Spreadsheets"] = "Spreadsheets (XLS)";
        ru["FM_Props_Models3D"] = "3D Модели"; en["FM_Props_Models3D"] = "3D Models";
        ru["FM_Props_Other"] = "Прочие файлы"; en["FM_Props_Other"] = "Other Files";
        ru["FM_Props_Open"] = "Открыть"; en["FM_Props_Open"] = "Open";
        ru["FM_Props_Delete"] = "Удалить"; en["FM_Props_Delete"] = "Delete";
        ru["FM_Props_SetPrimary"] = "Сделать главной"; en["FM_Props_SetPrimary"] = "Set as primary";
        ru["FM_Props_Add"] = "+ Добавить"; en["FM_Props_Add"] = "+ Add";
        ru["FM_Props_NoAttributes"] = "Атрибуты не извлечены"; en["FM_Props_NoAttributes"] = "No attributes extracted";
        ru["FM_Props_NoAttributesDesc"] = "Для извлечения атрибутов семейство будет временно загружено в Revit"; en["FM_Props_NoAttributesDesc"] = "To extract attributes, the family will be temporarily loaded into Revit";
        ru["FM_Props_PresetCategory"] = "Категория: {0}"; en["FM_Props_PresetCategory"] = "Category: {0}";
        ru["FM_Props_NoPresets"] = "Нет пресетов для этой категории"; en["FM_Props_NoPresets"] = "No presets for this category";
        ru["FM_Props_3DComingSoon"] = "3D-просмотр модели"; en["FM_Props_3DComingSoon"] = "3D model preview";
        ru["FM_Props_3DDesc"] = "Прокрутите колесо мыши для масштабирования. Перетаскивайте правой кнопкой для вращения. Перетаскивайте левой кнопкой для панорамирования."; en["FM_Props_3DDesc"] = "Scroll wheel to zoom. Right-drag to rotate. Left-drag to pan.";
        ru["FM_3D_ResetView"] = "Сбросить вид"; en["FM_3D_ResetView"] = "Reset view";
        ru["FM_3D_ZoomExtents"] = "Показать всё"; en["FM_3D_ZoomExtents"] = "Zoom extents";
        ru["FM_3D_Wireframe"] = "Каркас"; en["FM_3D_Wireframe"] = "Wireframe";
        ru["FM_3D_Loading"] = "Загрузка 3D модели..."; en["FM_3D_Loading"] = "Loading 3D model...";
        ru["FM_3D_NoPreview"] = "3D-превью недоступно для этой версии"; en["FM_3D_NoPreview"] = "No 3D preview for this version";
        ru["FM_3D_UnsupportedNet48"] = "3D-просмотр недоступен на Revit 2019-2024. Используйте Revit 2025+ для отображения интерактивного 3D-просмотра."; en["FM_3D_UnsupportedNet48"] = "3D preview is unavailable on Revit 2019-2024. Use Revit 2025+ for interactive 3D preview.";
        ru["FM_3D_InitFailed"] = "Не удалось инициализировать 3D-просмотрщик. Проверьте, что DirectX 11 доступен на этой системе."; en["FM_3D_InitFailed"] = "Failed to initialize 3D viewer. Verify DirectX 11 is available on this system.";
        ru["FM_3D_LoadFailed"] = "Не удалось загрузить 3D-превью. Проверьте лог smartcon.log для деталей."; en["FM_3D_LoadFailed"] = "Failed to load 3D preview. Check smartcon.log for details.";
        ru["FM_Props_FileInfo"] = "Информация о файле"; en["FM_Props_FileInfo"] = "File Information";
        ru["FM_Props_Title"] = "Свойства семейства"; en["FM_Props_Title"] = "Family Properties";
        ru["FM_Props_NoAssets"] = "Нет файлов"; en["FM_Props_NoAssets"] = "No files";
        ru["FM_Props_ConfigurePreset"] = "Настроить пресет..."; en["FM_Props_ConfigurePreset"] = "Configure preset...";
        ru["FM_Props_ExtractAttributes"] = "Извлечь атрибуты"; en["FM_Props_ExtractAttributes"] = "Extract attributes";
        ru["FM_Props_NoCategoryAttr"] = "Семейству не назначена категория. Назначьте категорию, чтобы определить обязательные атрибуты."; en["FM_Props_NoCategoryAttr"] = "No category assigned. Assign a category to define required attributes.";
        ru["FM_Props_NoBindingsAttr"] = "Для категории нет обязательных атрибутов."; en["FM_Props_NoBindingsAttr"] = "No required attributes for this category.";
        ru["FM_Props_NotImported"] = "Атрибуты ещё не импортированы"; en["FM_Props_NotImported"] = "Attributes not yet imported";
        ru["FM_Props_NotImportedDesc"] = "Используйте команду «Импорт данных» из контекстного меню семейства в основной панели."; en["FM_Props_NotImportedDesc"] = "Use the 'Import Data' command from the family's context menu in the main panel.";
        ru["FM_Props_Completeness"] = "Полнота"; en["FM_Props_Completeness"] = "Completeness";
        ru["FM_Props_TypeSize"] = "Типоразмер"; en["FM_Props_TypeSize"] = "Type";
        ru["FM_Props_XlsNote"] = "XLS — рабочий файл, CSV — для Revit Lookup Table"; en["FM_Props_XlsNote"] = "XLS — working file, CSV — for Revit Lookup Table";
        ru["FM_Props_CategoryAll"] = "Все"; en["FM_Props_CategoryAll"] = "All";
        ru["FM_Props_AttributesAll"] = "Все"; en["FM_Props_AttributesAll"] = "All";
        ru["FM_Props_AttributesNoGroup"] = "Без группы"; en["FM_Props_AttributesNoGroup"] = "No group";
        ru["FM_Props_Tables"] = "Таблицы"; en["FM_Props_Tables"] = "Tables";
        ru["FM_Props_AttachToVersion"] = "Привязать к версии"; en["FM_Props_AttachToVersion"] = "Attach to version";
        ru["FM_Props_AttachToVersionHint"] = "Файл будет виден только для этой версии"; en["FM_Props_AttachToVersionHint"] = "File will be visible only for this version";
        ru["FM_Props_EmptyStateTitle"] = "Нет файлов"; en["FM_Props_EmptyStateTitle"] = "No files";
        ru["FM_Props_EmptyStateHint"] = "Нажмите «+ Добавить файл», чтобы загрузить"; en["FM_Props_EmptyStateHint"] = "Click \"+ Add file\" to upload";
        ru["FM_Props_AddFileUnified"] = "+ Добавить файл"; en["FM_Props_AddFileUnified"] = "+ Add file";
        ru["FM_Props_ConfirmDeleteAssetTitle"] = "Удаление файла"; en["FM_Props_ConfirmDeleteAssetTitle"] = "Delete file";
        ru["FM_Props_ConfirmDeleteAssetBody"] = "Удалить файл «{0}»? Это действие необратимо."; en["FM_Props_ConfirmDeleteAssetBody"] = "Delete file \"{0}\"? This action is irreversible.";

        // #131: avatar crop dialog
        ru["FM_Crop_Title"] = "Кадрирование аватарки"; en["FM_Crop_Title"] = "Crop Avatar";
        ru["FM_Crop_Apply"] = "Применить"; en["FM_Crop_Apply"] = "Apply";
        ru["FM_Crop_Cancel"] = "Отмена"; en["FM_Crop_Cancel"] = "Cancel";
        ru["FM_Crop_Reset"] = "Сбросить"; en["FM_Crop_Reset"] = "Reset";
        ru["FM_Crop_Zoom"] = "Масштаб"; en["FM_Crop_Zoom"] = "Zoom";
        ru["FM_Crop_OpenError"] = "Не удалось открыть изображение. Проверьте, что файл не повреждён и доступен для чтения."; en["FM_Crop_OpenError"] = "Failed to open the image. Verify the file is not corrupted and is readable.";
        ru["FM_Crop_RenderError"] = "Не удалось кадрировать изображение. Проверьте, что файл не повреждён."; en["FM_Crop_RenderError"] = "Failed to crop the image. Verify the file is not corrupted.";
        ru["FM_Crop_Preview"] = "Результат"; en["FM_Crop_Preview"] = "Preview";
        ru["FM_Crop_CoverHint"] = "Так будет выглядеть аватарка. Если область не 4:3, по краям останутся пустые поля."; en["FM_Crop_CoverHint"] = "This is what the avatar will look like. If the area is not 4:3, empty margins will remain on the sides.";

        ru["FM_PE_Title"] = "Редактор пресета атрибутов"; en["FM_PE_Title"] = "Attribute Preset Editor";
        ru["FM_PE_ParameterName"] = "Имя параметра"; en["FM_PE_ParameterName"] = "Parameter Name";
        ru["FM_PE_DisplayName"] = "Отображаемое имя"; en["FM_PE_DisplayName"] = "Display Name";
        ru["FM_PE_AddParameter"] = "+ Добавить параметр"; en["FM_PE_AddParameter"] = "+ Add parameter";
        ru["FM_PE_RemoveParameter"] = "- Удалить"; en["FM_PE_RemoveParameter"] = "- Remove";

        ru["FM_FamilyNotFoundAfterLoad"] = "Семейство не найдено после загрузки"; en["FM_FamilyNotFoundAfterLoad"] = "Family not found after loading";
        ru["FM_FamilyNotLoaded"] = "Семейство \"{0}\" не загружено в проект. Используйте \"Загрузить в проект\"."; en["FM_FamilyNotLoaded"] = "Family \"{0}\" not loaded in project. Use 'Load to Project'.";

        ru["FM_AL_Title"] = "Библиотека атрибутов"; en["FM_AL_Title"] = "Attribute Library";
        ru["FM_AL_Search"] = "Поиск атрибутов..."; en["FM_AL_Search"] = "Search attributes...";
        ru["FM_AL_Name"] = "Имя"; en["FM_AL_Name"] = "Name";
        ru["FM_AL_Group"] = "Группа"; en["FM_AL_Group"] = "Group";
        ru["FM_AL_Active"] = "Активен"; en["FM_AL_Active"] = "Active";
        ru["FM_AL_UsedIn"] = "Используется в"; en["FM_AL_UsedIn"] = "Used in";
        ru["FM_AL_Delete"] = "Удалить"; en["FM_AL_Delete"] = "Delete";
        ru["FM_AL_Close"] = "Закрыть"; en["FM_AL_Close"] = "Close";
        ru["FM_AL_ConfirmDelete"] = "Удалить атрибут \"{0}\"? Он используется в {1} категориях."; en["FM_AL_ConfirmDelete"] = "Delete attribute \"{0}\"? It is used in {1} categories.";
        ru["FM_AL_ConfirmDeleteEmpty"] = "Удалить атрибут \"{0}\"?"; en["FM_AL_ConfirmDeleteEmpty"] = "Delete attribute \"{0}\"?";
        ru["FM_AL_Add"] = "Добавить"; en["FM_AL_Add"] = "Add";
        ru["FM_AL_Rename"] = "Переименовать"; en["FM_AL_Rename"] = "Rename";
        ru["FM_AL_SetGroup"] = "Группа"; en["FM_AL_SetGroup"] = "Group";
        ru["FM_AL_EnterName"] = "Имя атрибута:"; en["FM_AL_EnterName"] = "Attribute name:";
        ru["FM_AL_EnterGroup"] = "Имя группы:"; en["FM_AL_EnterGroup"] = "Group name:";
        ru["FM_AL_DeactivateTitle"] = "Деактивация атрибута"; en["FM_AL_DeactivateTitle"] = "Deactivate Attribute";
        ru["FM_AL_DeactivateMessage"] = "Атрибут используется в {0} категориях. При деактивации все привязки будут удалены. Продолжить?"; en["FM_AL_DeactivateMessage"] = "Attribute is used in {0} categories. Deactivating will remove all bindings. Continue?";
        ru["FM_AL_FromSharedParams"] = "Из ФОП"; en["FM_AL_FromSharedParams"] = "From SP file";
        ru["FM_AL_ImportedFromSP"] = "Добавлено из ФОП: {0}. Нажмите OK для сохранения."; en["FM_AL_ImportedFromSP"] = "Added from SP file: {0}. Click OK to save.";

        ru["FM_SP_Title"] = "Импорт из файла общих параметров"; en["FM_SP_Title"] = "Import from Shared Parameters";
        ru["FM_SP_Browse"] = "Обзор…"; en["FM_SP_Browse"] = "Browse…";
        ru["FM_SP_BrowseTitle"] = "Выберите файл общих параметров"; en["FM_SP_BrowseTitle"] = "Select shared parameters file";
        ru["FM_SP_PathPlaceholder"] = "Путь к файлу общих параметров (.txt)"; en["FM_SP_PathPlaceholder"] = "Shared parameters file path (.txt)";
        ru["FM_SP_Search"] = "Поиск параметров..."; en["FM_SP_Search"] = "Search parameters...";
        ru["FM_SP_ColName"] = "Имя"; en["FM_SP_ColName"] = "Name";
        ru["FM_SP_ColDescription"] = "Описание"; en["FM_SP_ColDescription"] = "Description";
        ru["FM_SP_SelectAll"] = "Выбрать все"; en["FM_SP_SelectAll"] = "Select all";
        ru["FM_SP_DeselectAll"] = "Снять все"; en["FM_SP_DeselectAll"] = "Clear all";
        ru["FM_SP_Add"] = "Добавить"; en["FM_SP_Add"] = "Add";
        ru["FM_SP_SelectedFormat"] = "Выбрано: {0} из {1}"; en["FM_SP_SelectedFormat"] = "Selected: {0} of {1}";
        ru["FM_SP_AlreadyExists"] = "(уже есть)"; en["FM_SP_AlreadyExists"] = "(exists)";
        ru["FM_SP_ParseError"] = "Не удалось прочитать файл общих параметров: {0}"; en["FM_SP_ParseError"] = "Failed to read shared parameters file: {0}";
        ru["FM_SP_NoParams"] = "В файле не найдено параметров"; en["FM_SP_NoParams"] = "No parameters found in file";
        ru["FM_SP_NothingSelected"] = "Не выбрано ни одного атрибута"; en["FM_SP_NothingSelected"] = "No attributes selected";
        ru["FM_SP_CachedFileMissing"] = "Ранее выбранный файл не найден. Выберите файл заново."; en["FM_SP_CachedFileMissing"] = "Previously selected file was not found. Please browse again.";
        ru["FM_SP_AllGroups"] = "Все группы"; en["FM_SP_AllGroups"] = "All groups";

        ru["FM_Profile"] = "Профиль"; en["FM_Profile"] = "Profile";
        ru["FM_ProfileTitle"] = "Профиль пользователя"; en["FM_ProfileTitle"] = "User Profile";
        ru["FM_ProfileRole"] = "Роль"; en["FM_ProfileRole"] = "Role";
        ru["FM_ProfileUsers"] = "Пользователи базы"; en["FM_ProfileUsers"] = "Database Users";
        ru["FM_ProfileUsersCount"] = "пользователей"; en["FM_ProfileUsersCount"] = "users";
        ru["FM_ProfileClose"] = "Закрыть"; en["FM_ProfileClose"] = "Close";
        ru["FM_ProfileYourRole"] = "Ваша роль: {0}"; en["FM_ProfileYourRole"] = "Your role: {0}";
        ru["FM_ProfileEngineerInfo"] = "Доступны просмотр и загрузка семейств"; en["FM_ProfileEngineerInfo"] = "Browse and load families available";
        ru["FM_ProfileBimMasterInfo"] = "Управление пользователями и импорт семейств"; en["FM_ProfileBimMasterInfo"] = "User management and family import";
        ru["FM_ProfileDeleteTitle"] = "Удалить пользователя"; en["FM_ProfileDeleteTitle"] = "Remove User";
        ru["FM_ProfileDeletePrompt"] = "Удалить \"{0}\" из базы данных?\nПользователь сможет подключиться заново как Инженер."; en["FM_ProfileDeletePrompt"] = "Remove \"{0}\" from this database?\nThey will be able to reconnect as Engineer.";
        ru["FM_TransferOwnership"] = "Передать владение"; en["FM_TransferOwnership"] = "Transfer Ownership";
        ru["FM_TransferTitle"] = "Передача владения"; en["FM_TransferTitle"] = "Transfer Ownership";
        ru["FM_TransferNoBimMaster"] = "Нет BIM-Мастеров для передачи владения."; en["FM_TransferNoBimMaster"] = "No BIM Masters to transfer ownership to.";
        ru["FM_TransferConfirm"] = "Вы станете BIM-Мастером. Продолжить?"; en["FM_TransferConfirm"] = "You will become a BIM Master. Continue?";
        ru["FM_RoleChangeConfirmTitle"] = "Подтверждение смены роли"; en["FM_RoleChangeConfirmTitle"] = "Confirm Role Change";
        ru["FM_RoleChangeConfirmMessage"] = "Вы уверены, что хотите изменить роль этого пользователя?"; en["FM_RoleChangeConfirmMessage"] = "Are you sure you want to change this user's role?";
        ru["FM_RoleOwner"] = "Владелец"; en["FM_RoleOwner"] = "Owner";
        ru["FM_RoleBimMaster"] = "BIM-Мастер"; en["FM_RoleBimMaster"] = "BIM Master";
        ru["FM_RoleEngineer"] = "Инженер"; en["FM_RoleEngineer"] = "Engineer";
        ru["FM_AccessDenied"] = "Доступ запрещён"; en["FM_AccessDenied"] = "Access Denied";
        ru["FM_AccessDeniedMessage"] = "Владелец базы данных \"{0}\" ограничил вам доступ."; en["FM_AccessDeniedMessage"] = "The owner of \"{0}\" has restricted your access.";
        ru["FM_AccessDeniedContact"] = "Обратитесь к владельцу для получения разрешения."; en["FM_AccessDeniedContact"] = "Contact the owner for permission.";
        ru["FM_AccessDeniedOwner"] = "Владелец: {0}"; en["FM_AccessDeniedOwner"] = "Owner: {0}";
        ru["FM_StatusBanned"] = "Заблокирован"; en["FM_StatusBanned"] = "Banned";
        ru["FM_DbReadOnlyError"] = "База данных доступна только для чтения. Измените права доступа к файлу или обратитесь к администратору."; en["FM_DbReadOnlyError"] = "Database is read-only. Change file permissions or contact your administrator.";
        ru["FM_ProfileDisabledTooltip"] = "Подключите базу данных для просмотра профиля"; en["FM_ProfileDisabledTooltip"] = "Connect a database to view profile";
        ru["FM_StatusNoDatabase"] = "База данных не подключена"; en["FM_StatusNoDatabase"] = "No database connected";
        ru["FM_FamilyDeleteInUse"] = "Не удалось удалить файлы семейства. Возможно, файл открыт в Revit или другом приложении. Закройте файл и попробуйте снова."; en["FM_FamilyDeleteInUse"] = "Failed to delete family files. The file may be open in Revit or another application. Close the file and try again.";
        ru["FM_Tip_FindInCatalog"] = "Найти выделенное семейство в каталоге"; en["FM_Tip_FindInCatalog"] = "Find selected family in catalog";
        ru["FM_FindInCatalog_NoSelection"] = "В модели не выделено ни одного элемента"; en["FM_FindInCatalog_NoSelection"] = "No element selected in the model";
        ru["FM_FindInCatalog_NotFound"] = "Семейство '{0}' не найдено в каталоге"; en["FM_FindInCatalog_NotFound"] = "Family '{0}' not found in catalog";
        ru["FM_FindInCatalog_Found"] = "Найдено семейство: {0}"; en["FM_FindInCatalog_Found"] = "Family found: {0}";

        // Batch Import Dialog
        ru["FM_BatchImport_Title"] = "Импорт семейств"; en["FM_BatchImport_Title"] = "Import Families";
        ru["FM_BatchImport_FileName"] = "Имя файла"; en["FM_BatchImport_FileName"] = "File Name";
        ru["FM_BatchImport_RevitVersion"] = "Версия Revit"; en["FM_BatchImport_RevitVersion"] = "Revit Version";
        ru["FM_BatchImport_Status"] = "Статус"; en["FM_BatchImport_Status"] = "Status";
        ru["FM_BatchImport_Action"] = "Действие"; en["FM_BatchImport_Action"] = "Action";
        ru["FM_BatchImport_StatusNew"] = "Новое"; en["FM_BatchImport_StatusNew"] = "New";
        ru["FM_BatchImport_StatusExisting"] = "Существующее"; en["FM_BatchImport_StatusExisting"] = "Existing";
        ru["FM_BatchImport_StatusDuplicate"] = "Дубликат"; en["FM_BatchImport_StatusDuplicate"] = "Duplicate";
        ru["FM_BatchImport_StatusError"] = "Ошибка"; en["FM_BatchImport_StatusError"] = "Error";
        ru["FM_BatchImport_ActionIncrement"] = "Новая версия"; en["FM_BatchImport_ActionIncrement"] = "New Version";
        ru["FM_BatchImport_ActionOverwrite"] = "Перезаписать текущую"; en["FM_BatchImport_ActionOverwrite"] = "Overwrite Current";
        ru["FM_BatchImport_ActionSkip"] = "Пропустить"; en["FM_BatchImport_ActionSkip"] = "Skip";
        ru["FM_BatchImport_Load"] = "Загрузить"; en["FM_BatchImport_Load"] = "Load";
        ru["FM_BatchImport_Cancel"] = "Отмена"; en["FM_BatchImport_Cancel"] = "Cancel";
        ru["FM_BatchImport_SelectAll"] = "Выбрать все"; en["FM_BatchImport_SelectAll"] = "Select All";
        ru["FM_BatchImport_Stale"] = "Устарело"; en["FM_BatchImport_Stale"] = "Stale";
        ru["FM_BatchImport_TypeCount"] = "Типов"; en["FM_BatchImport_TypeCount"] = "Types";
        ru["FM_BatchImport_Stop"] = "Остановить"; en["FM_BatchImport_Stop"] = "Stop";
        ru["FM_BatchImport_Resume"] = "Продолжить"; en["FM_BatchImport_Resume"] = "Resume";
        ru["FM_BatchImport_Close"] = "Закрыть"; en["FM_BatchImport_Close"] = "Close";
        ru["FM_BatchImport_OK"] = "OK"; en["FM_BatchImport_OK"] = "OK";
        ru["FM_BatchImport_Stopping"] = "Останавливаю..."; en["FM_BatchImport_Stopping"] = "Stopping...";
        ru["FM_BatchImport_Paused"] = "Остановлено: обработано {0} из {1}"; en["FM_BatchImport_Paused"] = "Stopped: processed {0} of {1}";
        ru["FM_BatchImport_ProgressStaging"] = "Подготовка {0} из {1} — {2}"; en["FM_BatchImport_ProgressStaging"] = "Staging {0} of {1} — {2}";
        ru["FM_BatchImport_ProgressImporting"] = "Импорт {0} из {1} — {2}"; en["FM_BatchImport_ProgressImporting"] = "Importing {0} of {1} — {2}";
        ru["FM_BatchImport_ProgressExtracting"] = "Обработка {0} из {1} — {2}"; en["FM_BatchImport_ProgressExtracting"] = "Processing {0} of {1} — {2}";
        ru["FM_BatchImport_Finalizing"] = "Завершение..."; en["FM_BatchImport_Finalizing"] = "Finalizing...";
        ru["FM_BatchImport_SummaryFormat"] = "Импортировано: {0}, пропущено: {1}, ошибок: {2}"; en["FM_BatchImport_SummaryFormat"] = "Imported: {0}, skipped: {1}, errors: {2}";
        ru["FM_BatchImport_CrossNameDuplicate_Tooltip"] = "Содержимое совпадает с семейством \"{0}\" ({1}), хотя имя файла другое.\n\"Сделать активной\" — файл не импортируется, активируется найденная версия.\n\"Новая версия\" — семейство \"{0}\" будет переименовано в имя этого файла."; en["FM_BatchImport_CrossNameDuplicate_Tooltip"] = "Content matches family \"{0}\" ({1}) although the file name differs.\n\"Make Active\" — the file is not imported; the matched version is activated.\n\"New Version\" — family \"{0}\" will be renamed to this file's name.";
        ru["FM_BatchImport_CategoryMoveWarning_Tooltip"] = "\"{0}\" будет перемещено из \"{1}\" в \"{2}\" при импорте."; en["FM_BatchImport_CategoryMoveWarning_Tooltip"] = "\"{0}\" will be moved from \"{1}\" to \"{2}\" on import.";
        ru["FM_CategoryProvenance_Command"] = "Задано командой «Импорт в категорию»"; en["FM_CategoryProvenance_Command"] = "Set by the 'Import to Category' command";
        ru["FM_CategoryProvenance_Manual"] = "Выбрано вами"; en["FM_CategoryProvenance_Manual"] = "Picked by you";
        ru["FM_CategoryProvenance_AutoName"] = "Из каталога (совпадение имени)"; en["FM_CategoryProvenance_AutoName"] = "From catalog (name match)";
        ru["FM_CategoryProvenance_AutoHash"] = "Из дубликата (совпадение содержимого)"; en["FM_CategoryProvenance_AutoHash"] = "From duplicate (content match)";
        ru["FM_CategoryProvenance_None"] = "Категория не назначена"; en["FM_CategoryProvenance_None"] = "No category assigned";

        // Import Validation Gate (status column tooltips)
        ru["FM_Gate_Tooltip_NotChecked"] = "Файл прочитан. Категория не назначена — правила не проверялись."; en["FM_Gate_Tooltip_NotChecked"] = "File read. No category assigned — rules not checked.";
        ru["FM_Gate_Tooltip_Checking"] = "Проверка по правилам категории…"; en["FM_Gate_Tooltip_Checking"] = "Checking category rules…";
        ru["FM_Gate_Tooltip_Passed"] = "Проверка пройдена"; en["FM_Gate_Tooltip_Passed"] = "Check passed";
        ru["FM_Gate_Tooltip_PassedRules"] = "Проверка пройдена ({0} правил)"; en["FM_Gate_Tooltip_PassedRules"] = "Passed {0} rules";
        ru["FM_Gate_Tooltip_Warning"] = "Предупреждения в семействе: {0}. Импорт разрешён."; en["FM_Gate_Tooltip_Warning"] = "Family warnings: {0}. Import allowed.";
        ru["FM_Gate_Tooltip_FailedHealth"] = "Системные ошибки в семействе: {0}. Импорт заблокирован."; en["FM_Gate_Tooltip_FailedHealth"] = "System errors in the family: {0}. Import blocked.";
        ru["FM_Gate_Tooltip_FailedRules"] = "Нарушены правила категории: {0}. Импорт заблокирован."; en["FM_Gate_Tooltip_FailedRules"] = "Rule violations: {0}. Import blocked.";
        ru["FM_Gate_Tooltip_FailedBoth"] = "Системные ошибки: {0}, нарушения правил: {1}. Импорт заблокирован."; en["FM_Gate_Tooltip_FailedBoth"] = "System errors: {0}, rule violations: {1}. Import blocked.";
        ru["FM_Gate_Tooltip_Imported"] = "Импорт выполнен — открыть отчёт о проверке"; en["FM_Gate_Tooltip_Imported"] = "Import completed — open the validation report";

        // Validation Report dialog
        ru["FM_ValidationReport_Title"] = "Отчёт о проверке"; en["FM_ValidationReport_Title"] = "Validation Report";
        ru["FM_ValidationReport_Close"] = "Закрыть"; en["FM_ValidationReport_Close"] = "Close";
        ru["FM_ValidationReport_ColSection"] = "Проверка"; en["FM_ValidationReport_ColSection"] = "Section";
        ru["FM_ValidationReport_ColType"] = "Тип"; en["FM_ValidationReport_ColType"] = "Type";
        ru["FM_ValidationReport_ColAttribute"] = "Атрибут"; en["FM_ValidationReport_ColAttribute"] = "Attribute";
        ru["FM_ValidationReport_ColCheck"] = "Условие"; en["FM_ValidationReport_ColCheck"] = "Check";
        ru["FM_ValidationReport_ColExpected"] = "Ожидалось"; en["FM_ValidationReport_ColExpected"] = "Expected";
        ru["FM_ValidationReport_ColActual"] = "Фактически"; en["FM_ValidationReport_ColActual"] = "Actual";
        ru["FM_ValidationReport_SectionHealth"] = "Системная"; en["FM_ValidationReport_SectionHealth"] = "System";
        ru["FM_ValidationReport_SectionRules"] = "Правила"; en["FM_ValidationReport_SectionRules"] = "Rules";
        ru["FM_ValidationReport_EmptyValue"] = "<пусто>"; en["FM_ValidationReport_EmptyValue"] = "<empty>";
        ru["FM_ValidationReport_SummaryPassed"] = "Все проверки пройдены (для категории не заданы правила)"; en["FM_ValidationReport_SummaryPassed"] = "All checks passed (no rules configured for the category)";
        ru["FM_ValidationReport_SummaryPassedRules"] = "Все проверки пройдены ({0} правил)"; en["FM_ValidationReport_SummaryPassedRules"] = "All checks passed ({0} rules)";
        ru["FM_ValidationReport_SummaryFailed"] = "Проверка не пройдена — {0}"; en["FM_ValidationReport_SummaryFailed"] = "Check failed — {0}";
        ru["FM_ValidationReport_SummaryHealthErrors"] = "системные ошибки: {0}"; en["FM_ValidationReport_SummaryHealthErrors"] = "system errors: {0}";
        ru["FM_ValidationReport_SummaryHealthWarnings"] = "предупреждения: {0}"; en["FM_ValidationReport_SummaryHealthWarnings"] = "warnings: {0}";
        ru["FM_ValidationReport_SummaryRuleViolations"] = "нарушений правил: {0} (правил: {1}, типов: {2})"; en["FM_ValidationReport_SummaryRuleViolations"] = "rule violations: {0} (rules: {1}, types: {2})";
        ru["FM_ValidationReport_HealthSkipped"] = "Системная проверка: не выполнялась"; en["FM_ValidationReport_HealthSkipped"] = "System check: not performed";
        ru["FM_ValidationReport_HealthPassedLine"] = "Системная проверка: пройдена"; en["FM_ValidationReport_HealthPassedLine"] = "System check: passed";
        ru["FM_ValidationReport_HealthWarningsLine"] = "Системная проверка: предупреждений {0}"; en["FM_ValidationReport_HealthWarningsLine"] = "System check: {0} warning(s)";
        ru["FM_ValidationReport_HealthErrorsLine"] = "Системная проверка: ошибок {0}"; en["FM_ValidationReport_HealthErrorsLine"] = "System check: {0} error(s)";
        ru["FM_ValidationReport_RulesNone"] = "Правила категории: не заданы"; en["FM_ValidationReport_RulesNone"] = "Category rules: not configured";
        ru["FM_ValidationReport_RulesNotChecked"] = "Правила категории: не проверялись"; en["FM_ValidationReport_RulesNotChecked"] = "Category rules: not checked";
        ru["FM_ValidationReport_RulesPassedLine"] = "Правила категории: пройдены ({0} правил на {1} типах)"; en["FM_ValidationReport_RulesPassedLine"] = "Category rules: passed ({0} rules on {1} types)";
        ru["FM_ValidationReport_RulesViolationsLine"] = "Правила категории: нарушений {0} (правил: {1}, типов: {2})"; en["FM_ValidationReport_RulesViolationsLine"] = "Category rules: {0} violation(s) (rules: {1}, types: {2})";

        // Validation rule operators
        ru["FM_RuleOp_IsPresent"] = "Параметр присутствует"; en["FM_RuleOp_IsPresent"] = "Parameter exists";
        ru["FM_RuleOp_HasValue"] = "Заполнен"; en["FM_RuleOp_HasValue"] = "Has value";
        ru["FM_RuleOp_IsEmpty"] = "Пустой"; en["FM_RuleOp_IsEmpty"] = "Is empty";
        ru["FM_RuleOp_Equals"] = "Равно"; en["FM_RuleOp_Equals"] = "Equals";
        ru["FM_RuleOp_NotEquals"] = "Не равно"; en["FM_RuleOp_NotEquals"] = "Not equals";
        ru["FM_RuleOp_Contains"] = "Содержит"; en["FM_RuleOp_Contains"] = "Contains";
        ru["FM_RuleOp_NotContains"] = "Не содержит"; en["FM_RuleOp_NotContains"] = "Not contains";
        ru["FM_RuleOp_Between"] = "В диапазоне"; en["FM_RuleOp_Between"] = "Between";

        // Validation Rules Editor (category tree editor → attribute context menu)
        ru["FM_CTE_ValidationRules"] = "Правила валидации"; en["FM_CTE_ValidationRules"] = "Validation rules";
        ru["FM_CTE_RulesCount"] = "Правил валидации: {0}"; en["FM_CTE_RulesCount"] = "Validation rules: {0}";
        ru["FM_CTE_RulesCountDisabled"] = "Правил валидации: {0} (отключено: {1})"; en["FM_CTE_RulesCountDisabled"] = "Validation rules: {0} (disabled: {1})";
        ru["FM_CTE_RulesNone"] = "Правила валидации не заданы — нажмите для настройки"; en["FM_CTE_RulesNone"] = "No validation rules — click to configure";
        ru["FM_CTE_UnbindRulesTitle"] = "Правила валидации будут удалены"; en["FM_CTE_UnbindRulesTitle"] = "Validation rules will be deleted";
        ru["FM_CTE_UnbindRulesMessage"] = "У атрибута \"{0}\" заданы правила валидации ({1}). При отвязке они будут удалены без возможности восстановления. Продолжить?"; en["FM_CTE_UnbindRulesMessage"] = "Attribute \"{0}\" has validation rules ({1}). Unbinding will permanently delete them. Continue?";
        ru["FM_CTE_ImportedFull"] = "Импортировано: категорий новых {0} (существующих {1}), атрибутов {2}, привязок {3}, правил {4}"; en["FM_CTE_ImportedFull"] = "Imported: {0} new categories ({1} existing), {2} attributes, {3} bindings, {4} rules";
        ru["FM_CTE_ImportedSkipped"] = " (пропущено: {0})"; en["FM_CTE_ImportedSkipped"] = " (skipped: {0})";
        ru["FM_RulesEditor_Title"] = "Правила валидации"; en["FM_RulesEditor_Title"] = "Validation Rules";
        ru["FM_RulesEditor_Add"] = "Добавить правило"; en["FM_RulesEditor_Add"] = "Add rule";
        ru["FM_RulesEditor_Save"] = "Сохранить"; en["FM_RulesEditor_Save"] = "Save";
        ru["FM_RulesEditor_Cancel"] = "Отмена"; en["FM_RulesEditor_Cancel"] = "Cancel";
        ru["FM_RulesEditor_ColOperator"] = "Условие"; en["FM_RulesEditor_ColOperator"] = "Operator";
        ru["FM_RulesEditor_ColValue"] = "Значение"; en["FM_RulesEditor_ColValue"] = "Value";
        ru["FM_RulesEditor_ColEnabled"] = "Вкл."; en["FM_RulesEditor_ColEnabled"] = "On";
        ru["FM_RulesEditor_ErrorValueRequired"] = "Для этого условия требуется значение"; en["FM_RulesEditor_ErrorValueRequired"] = "Value is required for this operator";
        ru["FM_RulesEditor_ErrorNumberRequired"] = "Для этого условия требуется число"; en["FM_RulesEditor_ErrorNumberRequired"] = "A number is required for this operator";
        ru["FM_RulesEditor_ErrorRangeRequired"] = "Обе границы диапазона должны быть числами"; en["FM_RulesEditor_ErrorRangeRequired"] = "Both range bounds must be numbers";
        ru["FM_RulesEditor_ErrorRangeOrder"] = "Нижняя граница не должна превышать верхнюю"; en["FM_RulesEditor_ErrorRangeOrder"] = "The lower bound must not exceed the upper bound";

        // Category-change gate (DnD / properties picker)
        ru["FM_Gate_CategoryBlocked_Banner"] = "Категория «{0}» не может быть применена — семейство не проходит её правила. Перемещение отменено."; en["FM_Gate_CategoryBlocked_Banner"] = "Category \"{0}\" cannot be applied — the family fails its rules. The move was cancelled.";
        ru["FM_Gate_CategoryBlockedNoData_Title"] = "Категория не может быть применена"; en["FM_Gate_CategoryBlockedNoData_Title"] = "Category cannot be applied";
        ru["FM_Gate_CategoryBlockedNoData_Body"] = "Семейство «{0}» нельзя переместить в «{1}»: атрибуты не извлечены, проверить правила невозможно.\n\nВыполните «Обновить базу» и повторите."; en["FM_Gate_CategoryBlockedNoData_Body"] = "Family \"{0}\" cannot be moved to \"{1}\": attributes were not extracted, so the rules cannot be checked.\n\nRun \"Update database\" and try again.";

        // Hash Recalculation Migration (Issue #126)
        ru["FM_HashRecalc_LoadBlockedTitle"] = "Требуется обновление базы"; en["FM_HashRecalc_LoadBlockedTitle"] = "Database Update Required";
        ru["FM_HashRecalc_LoadBlockedBody"] = "Действие временно недоступно: база данных создана в старой версии SmartCon и требует обновления ({0} записей). До завершения обновления база работает в режиме просмотра.\n\nОбновить сейчас? Процесс можно прервать — он продолжится с места остановки."; en["FM_HashRecalc_LoadBlockedBody"] = "This action is temporarily unavailable: the database was created by an older SmartCon version and must be updated ({0} records). Until the update completes, the database is read-only.\n\nUpdate now? You can interrupt the process — it will resume from where it stopped.";
        ru["FM_HashRecalc_LoadBlockedBodyNewerRevit"] = "База данных требует обновления в Revit {0} или новее и работает в режиме просмотра. Откройте её в Revit {0}+ и выполните «Обновить базу» — тогда всё обновится за один раз."; en["FM_HashRecalc_LoadBlockedBodyNewerRevit"] = "The database must be updated in Revit {0} or newer and is read-only. Open it in Revit {0}+ and run \"Update database\" — everything will be updated in a single pass.";
        ru["FM_HashRecalc_LoadBlockedBodyReadOnlyRole"] = "База данных требует обновления и работает в режиме просмотра. Обновление может выполнить пользователь с ролью Owner или BIM-мастер — обратитесь к нему."; en["FM_HashRecalc_LoadBlockedBodyReadOnlyRole"] = "The database must be updated and is read-only. Only a user with the Owner or BIM Master role can run the update — please contact them.";
        ru["FM_HashRecalc_PurgeButton"] = "Удалить записи недоступных ({0})"; en["FM_HashRecalc_PurgeButton"] = "Delete unavailable records ({0})";
        ru["FM_HashRecalc_PurgeConfirmTitle"] = "Удаление записей"; en["FM_HashRecalc_PurgeConfirmTitle"] = "Delete records";
        ru["FM_HashRecalc_PurgeConfirmBody"] = "Удалить из каталога {0} записей о недоступных файлах? Действие нельзя отменить."; en["FM_HashRecalc_PurgeConfirmBody"] = "Delete {0} records of unavailable files from the catalog? This action cannot be undone.";
        ru["FM_HashRecalc_PurgeResult"] = "Удалено семейств: {0}, версий: {1}."; en["FM_HashRecalc_PurgeResult"] = "Families deleted: {0}, versions: {1}.";
        ru["FM_HashRecalc_PurgeDirsFailed"] = "Папки на диске удалить не удалось (нет доступа): {0} — удалите их вручную."; en["FM_HashRecalc_PurgeDirsFailed"] = "Could not delete directories on disk (access denied): {0} — please remove them manually.";

        // Unified Database Update Dialog (ADR-054)
        ru["FM_DbUpdate_Title"] = "Обновление базы"; en["FM_DbUpdate_Title"] = "Database Update";
        ru["FM_DbUpdate_Starting"] = "Подготовка..."; en["FM_DbUpdate_Starting"] = "Preparing...";
        ru["FM_DbUpdate_ProgressFormat"] = "Обработка {0} из {1} — {2}"; en["FM_DbUpdate_ProgressFormat"] = "Processing {0} of {1} — {2}";
        ru["FM_DbUpdate_Stopping"] = "Прерываю..."; en["FM_DbUpdate_Stopping"] = "Stopping...";
        ru["FM_DbUpdate_SummaryUpdated"] = "Обновлено записей: {0}"; en["FM_DbUpdate_SummaryUpdated"] = "Records updated: {0}";
        ru["FM_DbUpdate_SummaryFailed"] = "Не удалось обработать (будут предложены снова): {0}"; en["FM_DbUpdate_SummaryFailed"] = "Could not be processed (will be offered again): {0}";
        ru["FM_DbUpdate_SummaryNewerRevit"] = "Требуют более новой версии Revit: {0}"; en["FM_DbUpdate_SummaryNewerRevit"] = "Require a newer Revit version: {0}";
        ru["FM_DbUpdate_SummaryMissing"] = "Файлы не найдены на диске: {0}"; en["FM_DbUpdate_SummaryMissing"] = "Files not found on disk: {0}";
        ru["FM_DbUpdate_SummaryCancelled"] = "Прервано пользователем — обновление продолжится при следующем запуске."; en["FM_DbUpdate_SummaryCancelled"] = "Interrupted by user — the update will resume on the next launch.";
        ru["FM_DbUpdate_Cancel"] = "Прервать"; en["FM_DbUpdate_Cancel"] = "Interrupt";
        ru["FM_DbUpdate_Close"] = "Закрыть"; en["FM_DbUpdate_Close"] = "Close";

        ru["FM_AttrStatus_Found"] = "Найдено"; en["FM_AttrStatus_Found"] = "Found";
        ru["FM_AttrStatus_MissingParameter"] = "Параметр не найден"; en["FM_AttrStatus_MissingParameter"] = "Parameter not found";
        ru["FM_AttrStatus_EmptyValue"] = "Пустое значение"; en["FM_AttrStatus_EmptyValue"] = "Empty value";
        ru["FM_AttrStatus_UnsupportedType"] = "Неподдерживаемый тип"; en["FM_AttrStatus_UnsupportedType"] = "Unsupported type";
        ru["FM_AttrStatus_ReadError"] = "Ошибка чтения"; en["FM_AttrStatus_ReadError"] = "Read error";
        ru["FM_AttrStatus_NotInFamily"] = "Нет в семействе"; en["FM_AttrStatus_NotInFamily"] = "Not in family";

        ru["FM_LoadShared_DialogTitle"] = "Общее вложенное семейство — режим загрузки";
        en["FM_LoadShared_DialogTitle"] = "Shared nested family — loading mode";

        ru["FM_LoadShared_Header"] = "Загрузка общего вложенного семейства";
        en["FM_LoadShared_Header"] = "Loading shared nested family";

        ru["FM_LoadShared_Message"] = "Семейство «{0}» уже загружено в проект, но в загружаемой версии оно изменено. Выберите режим загрузки:";
        en["FM_LoadShared_Message"] = "Family \"{0}\" is already loaded in the project, but it has been modified in the loaded version. Choose a loading mode:";

        ru["FM_LoadShared_UseProject"] = "Использовать версию из проекта";
        en["FM_LoadShared_UseProject"] = "Use project version";

        ru["FM_LoadShared_UseProjectHint"] = "Оставить без изменений. Существующие типы и параметры в проекте сохранятся.";
        en["FM_LoadShared_UseProjectHint"] = "Leave unchanged. Existing types and parameters in the project will be preserved.";

        ru["FM_LoadShared_OverwriteParams"] = "Заменить параметры";
        en["FM_LoadShared_OverwriteParams"] = "Overwrite parameters";

        ru["FM_LoadShared_OverwriteParamsHint"] = "Загрузить новую версию семейства, параметры существующих типов будут обновлены.";
        en["FM_LoadShared_OverwriteParamsHint"] = "Load the new family version, parameter values of existing types will be overwritten.";

        ru["FM_LoadShared_OverwriteAll"] = "Заменить всё";
        en["FM_LoadShared_OverwriteAll"] = "Replace everything";

        ru["FM_LoadShared_OverwriteAllHint"] = "Полная перезапись семейства и всех его типов на новую версию.";
        en["FM_LoadShared_OverwriteAllHint"] = "Full overwrite of the family and all its types with the new version.";

        ru["FM_LoadShared_InUseWarning"] = "⚠ В проекте размещены экземпляры этого семейства. Перезапись может повлиять на них.";
        en["FM_LoadShared_InUseWarning"] = "⚠ Instances of this family are placed in the project. Overwrite may affect them.";

        ru["FM_LoadShared_Apply"] = "Применить";
        en["FM_LoadShared_Apply"] = "Apply";

        ru["FM_LoadShared_Skip"] = "Пропущено: {0}";
        en["FM_LoadShared_Skip"] = "Skipped: {0}";

        ru["FM_LoadShared_BatchProgress"] = "Конфликт №{0} — в файле {1} общих вложенных, Revit спрашивает только об изменённых";
        en["FM_LoadShared_BatchProgress"] = "Conflict #{0} — file has {1} shared nested families, Revit asks only for changed ones";

        ru["FM_LoadShared_SourceFromCatalog"] = "имя из каталога SmartCon";
        en["FM_LoadShared_SourceFromCatalog"] = "name from SmartCon catalog";

        ru["FM_LoadShared_SourcePlaceholder"] = "имя недоступно — переимпортируйте семейство в Family Manager";
        en["FM_LoadShared_SourcePlaceholder"] = "name unavailable — re-import the family in Family Manager";

        ru["FM_ToggleSubtreeTooltip"] = "Развернуть/свернуть вложенные категории";
        en["FM_ToggleSubtreeTooltip"] = "Toggle subtree";
        ru["FM_ExpandAllTooltip"] = "Развернуть всё дерево";
        en["FM_ExpandAllTooltip"] = "Expand all";
        ru["FM_CollapseAllTooltip"] = "Свернуть всё дерево";
        en["FM_CollapseAllTooltip"] = "Collapse all";
        ru["FM_TotalFamiliesTooltip"] = "Загружено семейств: {0}";
        en["FM_TotalFamiliesTooltip"] = "Total families loaded: {0}";

        // Project-base binding (Issue #119 / ADR-045)
        ru["FM_PBase_CreateGeneralDatabase"] = "Создать общую базу";
        en["FM_PBase_CreateGeneralDatabase"] = "Create general database";
        ru["FM_PBase_CreateProjectDatabase"] = "Создать базу проекта";
        en["FM_PBase_CreateProjectDatabase"] = "Create project base database";
        ru["FM_PBase_CreateDatabase"] = "Создать базу";
        en["FM_PBase_CreateDatabase"] = "Create database";
        ru["FM_PBase_ConnectDatabase"] = "Подключить базу";
        en["FM_PBase_ConnectDatabase"] = "Connect database";
        ru["FM_PBase_DisconnectDatabase"] = "Отключить базу";
        en["FM_PBase_DisconnectDatabase"] = "Disconnect database";
        ru["FM_PBase_ConfigureProjectBase"] = "Настроить правила проектной базы";
        en["FM_PBase_ConfigureProjectBase"] = "Configure project base";
        ru["FM_PBase_ConvertToProjectBase"] = "Сделать проектной базой";
        en["FM_PBase_ConvertToProjectBase"] = "Convert to project base";
        ru["FM_PBase_ConvertToProjectBaseTitle"] = "Преобразование в проектную базу";
        en["FM_PBase_ConvertToProjectBaseTitle"] = "Convert to project base";
        ru["FM_PBase_ConvertToGeneralBase"] = "Сделать общей базой";
        en["FM_PBase_ConvertToGeneralBase"] = "Convert to general base";
        ru["FM_PBase_ConvertToGeneralConfirmTitle"] = "Преобразование в общую базу";
        en["FM_PBase_ConvertToGeneralConfirmTitle"] = "Convert to general base";
        ru["FM_PBase_ConvertToGeneralConfirm"] = "База \"{0}\" перестанет автоматически активироваться по имени файла проекта. Шаблон привязки будет удалён. Продолжить?";
        en["FM_PBase_ConvertToGeneralConfirm"] = "Database \"{0}\" will stop auto-activating by project file name. The binding template will be deleted. Continue?";
        ru["FM_PBase_ConvertedToProject"] = "База \"{0}\" преобразована в проектную";
        en["FM_PBase_ConvertedToProject"] = "Database \"{0}\" converted to project base";
        ru["FM_PBase_ConvertedToGeneral"] = "База \"{0}\" преобразована в общую";
        en["FM_PBase_ConvertedToGeneral"] = "Database \"{0}\" converted to general base";
        ru["FM_PBase_ConvertErrorTitle"] = "Ошибка преобразования базы";
        en["FM_PBase_ConvertErrorTitle"] = "Database conversion error";
        ru["FM_PBase_ConvertError"] = "Ошибка преобразования базы: {0}";
        en["FM_PBase_ConvertError"] = "Error converting database: {0}";
        ru["FM_PBase_BindingNotConfiguredConvert"] = "Привязка к проекту не настроена. Нельзя преобразовать базу в проектную.";
        en["FM_PBase_BindingNotConfiguredConvert"] = "Project binding is not configured. Cannot convert to project base.";
        ru["FM_PBase_StatusProjectUnsaved"] = "Файл не сохранён — проектные базы недоступны. Сохраните файл, чтобы активировать базу проекта.";
        en["FM_PBase_StatusProjectUnsaved"] = "File not saved — project bases are unavailable. Save the file to activate a project base.";
        ru["FM_PBase_UnsavedFilePlaceholder"] = "(файл не сохранён)";
        en["FM_PBase_UnsavedFilePlaceholder"] = "(file not saved)";
        ru["FM_PBase_DeleteDatabase"] = "Удалить базу";
        en["FM_PBase_DeleteDatabase"] = "Delete database";
        ru["FM_PBase_DatabaseTools"] = "Инструменты базы";
        en["FM_PBase_DatabaseTools"] = "Database tools";
        ru["FM_PBase_UpdateDatabase"] = "Обновить базу";
        en["FM_PBase_UpdateDatabase"] = "Update database";
        ru["FM_PBase_UpdateDatabaseTooltip"] = "Обновить базу до актуального состояния";
        en["FM_PBase_UpdateDatabaseTooltip"] = "Update the database to the latest state";
        ru["FM_PBase_UpdateDatabaseBadgeTooltip"] = "Требуется обновление базы данных";
        en["FM_PBase_UpdateDatabaseBadgeTooltip"] = "Database update required";
        ru["FM_PBase_OptionalBadgeTooltip"] = "Есть рекомендуемые обновления базы — доступно в текущей версии Revit.";
        en["FM_PBase_OptionalBadgeTooltip"] = "Recommended database updates are available — can run in the current Revit version.";
        ru["FM_PBase_OptionalBadgeTooltipNewerRevit"] = "Есть рекомендуемые обновления базы — требуется Revit {0} или новее.";
        en["FM_PBase_OptionalBadgeTooltipNewerRevit"] = "Recommended database updates are available — Revit {0} or newer is required.";
        ru["FM_DbUpdate_BannerText"] = "База данных создана в старой версии SmartCon и работает в режиме просмотра. Обновите её, чтобы импортировать и изменять семейства.";
        en["FM_DbUpdate_BannerText"] = "The database was created by an older SmartCon version and is read-only. Update it to import and modify families.";
        ru["FM_DbUpdate_BannerTextNewerRevit"] = "База данных требует обновления в Revit {0} или новее и работает в режиме просмотра. Откройте её в Revit {0}+ и выполните «Обновить базу» — тогда всё обновится за один раз.";
        en["FM_DbUpdate_BannerTextNewerRevit"] = "The database must be updated in Revit {0} or newer and is read-only. Open it in Revit {0}+ and run \"Update database\" — everything will be updated in a single pass.";
        ru["FM_DbUpdate_BannerTextReadOnlyRole"] = "База данных требует обновления и работает в режиме просмотра. Обновление может выполнить пользователь с ролью Owner или BIM-мастер — обратитесь к нему.";
        en["FM_DbUpdate_BannerTextReadOnlyRole"] = "The database must be updated and is read-only. Only a user with the Owner or BIM Master role can run the update — please contact them.";
        ru["FM_DbUpdate_BannerButton"] = "Обновить";
        en["FM_DbUpdate_BannerButton"] = "Update";
        ru["FM_PluginGate_BannerText"] = "База данных обновлена до более новой версии SmartCon ({0}). Текущая версия приложения устарела: просмотр и загрузка семейств в проект доступны, но изменение базы недоступно. Обновите приложение, чтобы снять ограничение.";
        en["FM_PluginGate_BannerText"] = "This database was upgraded by a newer SmartCon ({0}). Your app version is outdated: browsing and loading families into the project are available, but modifying the database is not. Update the app to lift the restriction.";
        ru["FM_PluginGate_UpdateAppButton"] = "Обновить приложение";
        en["FM_PluginGate_UpdateAppButton"] = "Update app";
        ru["FM_HashRecalc_LoadBlockedBodyTeamNote"] = "Обратите внимание: после обновления пользователи со старыми версиями SmartCon не смогут редактировать эту базу (просмотр и загрузка в проект останутся доступны). Убедитесь, что команда обновилась.";
        en["FM_HashRecalc_LoadBlockedBodyTeamNote"] = "Note: after the update, users on older SmartCon versions will not be able to edit this database (browsing and loading into the project remain available). Make sure the team has updated.";
        ru["FM_PBase_Title"] = "Привязка базы проекта к имени файла";
        en["FM_PBase_Title"] = "Project Base Binding Rules";
        ru["FM_PBase_ProjectNameLabel"] = "Проект:";
        en["FM_PBase_ProjectNameLabel"] = "Project:";
        ru["FM_PBase_UseCurrentFile"] = "Подставить текущий";
        en["FM_PBase_UseCurrentFile"] = "Use current file";
        ru["FM_PBase_PreviewFileName"] = "Превью / тестовое имя файла";
        en["FM_PBase_PreviewFileName"] = "Preview / test file name";
        ru["FM_PBase_FileName"] = "Имя файла";
        en["FM_PBase_FileName"] = "File name";
        ru["FM_PBase_ParseResult"] = "Результат парсинга";
        en["FM_PBase_ParseResult"] = "Parse result";
        ru["FM_PBase_Preview"] = "Превью";
        en["FM_PBase_Preview"] = "Preview";
        ru["FM_PBase_Result"] = "Результат";
        en["FM_PBase_Result"] = "Result";
        ru["FM_PBase_NewField"] = "Новое поле";
        en["FM_PBase_NewField"] = "New Field";
        ru["FM_Error_Title"] = "Ошибка";
        en["FM_Error_Title"] = "Error";
        ru["FM_PBase_BindingNotConfigured"] = "Привязка к проекту не настроена. Нельзя создать проектную базу.";
        en["FM_PBase_BindingNotConfigured"] = "Project binding is not configured. Cannot create project base.";
        ru["FM_PBase_ParseRuleError"] = "Ошибка редактора правила парсинга:\n\n{0}";
        en["FM_PBase_ParseRuleError"] = "Parse rule editor error:\n\n{0}";
        ru["FM_PBase_FieldLibraryError"] = "Ошибка библиотеки полей:\n\n{0}";
        en["FM_PBase_FieldLibraryError"] = "Field library error:\n\n{0}";
        ru["FM_PBase_FileNameBlocks"] = "Блоки имени файла";
        en["FM_PBase_FileNameBlocks"] = "File name blocks";
        ru["FM_PBase_FieldLibrary"] = "Библиотека полей";
        en["FM_PBase_FieldLibrary"] = "Field library";
        ru["FM_PBase_AddBlock"] = "Добавить блок";
        en["FM_PBase_AddBlock"] = "Add block";
        ru["FM_PBase_RemoveBlock"] = "Удалить блок";
        en["FM_PBase_RemoveBlock"] = "Remove block";
        ru["FM_PBase_AddField"] = "Добавить поле";
        en["FM_PBase_AddField"] = "Add field";
        ru["FM_PBase_RemoveField"] = "Удалить поле";
        en["FM_PBase_RemoveField"] = "Remove field";
        ru["FM_PBase_TestParse"] = "Тестировать";
        en["FM_PBase_TestParse"] = "Test parse";
        ru["FM_PBase_StatusGeneral"] = "Общая база: {0}";
        en["FM_PBase_StatusGeneral"] = "General base: {0}";
        ru["FM_PBase_StatusProjectMatch"] = "Проектная база: {0} → {1}";
        en["FM_PBase_StatusProjectMatch"] = "Project base: {0} → {1}";
        ru["FM_PBase_StatusProjectMismatch"] = "База не подходит к проекту. Загрузка заблокирована.";
        en["FM_PBase_StatusProjectMismatch"] = "Base does not match project. Loading blocked.";
        ru["FM_PBase_StatusNoDatabase"] = "База данных не подключена";
        en["FM_PBase_StatusNoDatabase"] = "No database connected";
        ru["FM_PBase_Delimiter"] = "Разделитель";
        en["FM_PBase_Delimiter"] = "Delimiter";
        ru["FM_PBase_SegmentIndex"] = "Индекс";
        en["FM_PBase_SegmentIndex"] = "Index";
        ru["FM_PBase_SegmentCount"] = "Количество";
        en["FM_PBase_SegmentCount"] = "Count";
        ru["FM_PBase_CharOffset"] = "Смещение";
        en["FM_PBase_CharOffset"] = "Offset";
        ru["FM_PBase_CharCount"] = "Символов";
        en["FM_PBase_CharCount"] = "Chars";
        ru["FM_PBase_OpenMarker"] = "Открывающий";
        en["FM_PBase_OpenMarker"] = "Open";
        ru["FM_PBase_CloseMarker"] = "Закрывающий";
        en["FM_PBase_CloseMarker"] = "Close";
        ru["FM_PBase_Marker"] = "Маркер";
        en["FM_PBase_Marker"] = "Marker";
        ru["FM_PBase_MarkerIndex"] = "Индекс";
        en["FM_PBase_MarkerIndex"] = "Index";
        ru["FM_PBase_ParseMode"] = "Режим парсинга";
        en["FM_PBase_ParseMode"] = "Parse mode";
        ru["FM_PBase_ParseMode_Delimiter"] = "По разделителю";
        en["FM_PBase_ParseMode_Delimiter"] = "Delimiter";
        ru["FM_PBase_ParseMode_FixedWidth"] = "Фикс. ширина";
        en["FM_PBase_ParseMode_FixedWidth"] = "Fixed width";
        ru["FM_PBase_ParseMode_Between"] = "Между маркерами";
        en["FM_PBase_ParseMode_Between"] = "Between markers";
        ru["FM_PBase_ParseMode_After"] = "После маркера";
        en["FM_PBase_ParseMode_After"] = "After marker";
        ru["FM_PBase_ParseMode_Remainder"] = "Остаток";
        en["FM_PBase_ParseMode_Remainder"] = "Remainder";
        ru["FM_PBase_ParseMode_Delimiter_Desc"] = "Разбить по разделителю и выбрать сегмент";
        en["FM_PBase_ParseMode_Delimiter_Desc"] = "Split by delimiter and pick segment";
        ru["FM_PBase_ParseMode_FixedWidth_Desc"] = "Взять N символов с заданного смещения";
        en["FM_PBase_ParseMode_FixedWidth_Desc"] = "Take N characters from offset";
        ru["FM_PBase_ParseMode_Between_Desc"] = "Текст между открывающим и закрывающим маркером";
        en["FM_PBase_ParseMode_Between_Desc"] = "Text between opening and closing markers";
        ru["FM_PBase_ParseMode_After_Desc"] = "Текст после указанного маркера";
        en["FM_PBase_ParseMode_After_Desc"] = "Text after specified marker";
        ru["FM_PBase_ParseMode_Remainder_Desc"] = "Всё что осталось после предыдущих блоков";
        en["FM_PBase_ParseMode_Remainder_Desc"] = "Everything left after previous blocks";
        ru["FM_PBase_ValidationMode"] = "Режим валидации";
        en["FM_PBase_ValidationMode"] = "Validation mode";
        ru["FM_PBase_ValMode_None"] = "Любое";
        en["FM_PBase_ValMode_None"] = "Any";
        ru["FM_PBase_ValMode_List"] = "Список";
        en["FM_PBase_ValMode_List"] = "List";
        ru["FM_PBase_ValMode_Contains"] = "Содержит";
        en["FM_PBase_ValMode_Contains"] = "Contains";
        ru["FM_PBase_ValMode_Length"] = "Длина";
        en["FM_PBase_ValMode_Length"] = "Length";
        ru["FM_PBase_ValMode_None_Desc"] = "Без валидации";
        en["FM_PBase_ValMode_None_Desc"] = "No validation";
        ru["FM_PBase_ValMode_List_Desc"] = "Значение должно быть из списка";
        en["FM_PBase_ValMode_List_Desc"] = "Value must be in the list";
        ru["FM_PBase_ValMode_Contains_Desc"] = "Значение должно содержать хотя бы одну из подстрок";
        en["FM_PBase_ValMode_Contains_Desc"] = "Value must contain at least one of the substrings";
        ru["FM_PBase_ValMode_Length_Desc"] = "Длина должна быть в диапазоне";
        en["FM_PBase_ValMode_Length_Desc"] = "Length must be within range";
        ru["FM_PBase_MinLength"] = "Мин";
        en["FM_PBase_MinLength"] = "Min";
        ru["FM_PBase_MaxLength"] = "Макс";
        en["FM_PBase_MaxLength"] = "Max";
        ru["FM_PBase_AddValue"] = "Добавить";
        en["FM_PBase_AddValue"] = "Add";
        ru["FM_PBase_RemoveValue"] = "Удалить";
        en["FM_PBase_RemoveValue"] = "Remove";
        ru["FM_PBase_Title_ParseRule"] = "Правило парсинга";
        en["FM_PBase_Title_ParseRule"] = "Parse rule";
        ru["FM_PBase_Title_FieldLibrary"] = "Библиотека полей";
        en["FM_PBase_Title_FieldLibrary"] = "Field library";
        ru["FM_PBase_Title_AllowedValues"] = "Редактор валидации поля";
        en["FM_PBase_Title_AllowedValues"] = "Field validation editor";
        ru["FM_PBase_DuplicateField"] = "Дублировать";
        en["FM_PBase_DuplicateField"] = "Duplicate";
        ru["FM_PBase_ValidationOk"] = "Совпадение: {0}";
        en["FM_PBase_ValidationOk"] = "Matched: {0}";
        ru["FM_PBase_PreviewCurrent"] = "Текущее";
        en["FM_PBase_PreviewCurrent"] = "Current";
        ru["FM_PBase_PreviewParsed"] = "Распарсено";
        en["FM_PBase_PreviewParsed"] = "Parsed";
        ru["FM_PlaceSystemType"] = "Системный тип \"{0}\" — щёлкните для размещения";
        en["FM_PlaceSystemType"] = "System type \"{0}\" — click to place";
        ru["FM_PlaceSystemTypeManual"] = "Тип \"{0}\" загружен в проект. Разместите его вручную — например, изоляция применяется к существующей трубе или воздуховоду";
        en["FM_PlaceSystemTypeManual"] = "Type \"{0}\" is loaded into the project. Place it manually — e.g. insulation applies to an existing pipe or duct";
        ru["FM_ImportVersionGateTitle"] = "Импорт ограничен версией Revit";
        en["FM_ImportVersionGateTitle"] = "Import limited by Revit version";
        ru["FM_ImportVersionGateBody"] = "Следующие системные категории нельзя загрузить в библиотеку на Revit {0}:\n{1}\n\nОни не будут импортированы. Обновите Revit до требуемой версии, чтобы добавить их в каталог.";
        en["FM_ImportVersionGateBody"] = "The following system categories cannot be loaded into the library on Revit {0}:\n{1}\n\nThey will not be imported. Upgrade Revit to the required version to add them to the catalog.";
        ru["FM_ImportVersionGateItem"] = "• {0} — требуется Revit {1}+";
        en["FM_ImportVersionGateItem"] = "• {0} — requires Revit {1}+";
        ru["FM_SystemTypesSynced"] = "«{0}»: синхронизировано типов {1} из {2}";
        en["FM_SystemTypesSynced"] = "\"{0}\": synchronized {1} of {2} types";
        ru["FM_SystemTypesSyncedWithErrors"] = "«{0}»: синхронизировано типов {1} из {2}, ошибок: {3}";
        en["FM_SystemTypesSyncedWithErrors"] = "\"{0}\": synchronized {1} of {2} types, errors: {3}";
        ru["FM_SystemTypeNoTypes"] = "«{0}»: в каталоге нет типов — переимпортируйте мини-проект";
        en["FM_SystemTypeNoTypes"] = "\"{0}\": no types in the catalog — reimport the mini-project";
        ru["FM_SystemTypesNotConverged"] = "; не приведено к эталону: {0} (подробности — в журнале)";
        en["FM_SystemTypesNotConverged"] = "; not converged to reference: {0} (see the log)";
        ru["FM_PBase_ColIndex"] = "#";
        en["FM_PBase_ColIndex"] = "#";
        ru["FM_PBase_ColField"] = "Поле";
        en["FM_PBase_ColField"] = "Field";
        ru["FM_PBase_ColParseRule"] = "Правило";
        en["FM_PBase_ColParseRule"] = "Rule";
        ru["FM_PBase_ColValue"] = "Значение";
        en["FM_PBase_ColValue"] = "Value";
        ru["FM_PBase_ColStatus"] = "Статус";
        en["FM_PBase_ColStatus"] = "Status";
        ru["FM_PBase_ColDisplayName"] = "Отображаемое имя";
        en["FM_PBase_ColDisplayName"] = "Display name";
        ru["FM_PBase_ColDescription"] = "Описание";
        en["FM_PBase_ColDescription"] = "Description";
        ru["FM_PBase_ColValidation"] = "Валидация";
        en["FM_PBase_ColValidation"] = "Validation";
        ru["FM_PBase_MoveUp"] = "Вверх";
        en["FM_PBase_MoveUp"] = "Up";
        ru["FM_PBase_MoveDown"] = "Вниз";
        en["FM_PBase_MoveDown"] = "Down";
        ru["FM_PBase_ValidField"] = "✓";
        en["FM_PBase_ValidField"] = "✓";
        ru["FM_PBase_InvalidField"] = "✗";
        en["FM_PBase_InvalidField"] = "✗";
        ru["FM_PBase_ParseRule_Delimiter"] = "Разд.";
        en["FM_PBase_ParseRule_Delimiter"] = "Delim.";
        ru["FM_PBase_ParseRule_FixedOffset"] = "Фикс. со смещением";
        en["FM_PBase_ParseRule_FixedOffset"] = "Fixed offset";
        ru["FM_PBase_ParseRule_Fixed"] = "Фикс.";
        en["FM_PBase_ParseRule_Fixed"] = "Fixed";
        ru["FM_PBase_ParseRule_Chars"] = "симв.";
        en["FM_PBase_ParseRule_Chars"] = "chars";
        ru["FM_PBase_ParseRule_After"] = "После";
        en["FM_PBase_ParseRule_After"] = "After";
        ru["FM_PBase_ParseRule_Remainder"] = "Остаток";
        en["FM_PBase_ParseRule_Remainder"] = "Remainder";
        ru["FM_PBase_ParseRule_OpeningN"] = "открывающий #{0}";
        en["FM_PBase_ParseRule_OpeningN"] = "opening #{0}";
        ru["FM_PBase_ParseRule_ClosingN"] = "закрывающий #{0}";
        en["FM_PBase_ParseRule_ClosingN"] = "closing #{0}";
    }
}
