using System.IO;
using Autodesk.Revit.UI;
using SmartCon.Core.Deployment;
using SmartCon.Core.Logging;

namespace SmartCon.App.Diagnostics;

/// <summary>
/// Self-healing .addin manifest (ADR-051). On every startup the manifest in
/// %APPDATA%\Autodesk\Revit\Addins\{year}\SmartCon.addin is compared with the
/// expected content (generated by <see cref="SmartConAddinManifest"/>) and rewritten
/// if missing or outdated. This closes the gap where the Updater cannot refresh the
/// manifest and enables native ALC dependency isolation (ManifestSettings) on Revit 2026+
/// without requiring a reinstall. On Revit 2025 the manifest intentionally has no
/// ManifestSettings — isolation there is driven by Nice3point.Revit.Toolkit itself.
/// </summary>
internal static class AddinManifestHealer
{
    /// <summary>Normalizes EOLs and BOM so the comparison does not depend on the writer
    /// (bat/installer write CRLF, the healer writes the Core template).</summary>
    private static string Normalize(string text)
        => text.Replace("\r\n", "\n").TrimStart('﻿');

    public static void EnsureCurrent(UIControlledApplication application)
    {
        try
        {
            using var _scope = SmartConLogger.BeginScope("AddinHealer",
                ("Method", nameof(EnsureCurrent)));

            if (!int.TryParse(application.ControlledApplication.VersionNumber, out var year))
            {
                SmartConLogger.Warn(
                    "Cannot parse Revit VersionNumber — .addin manifest not verified " +
                    "[Action: check %APPDATA%\\Autodesk\\Revit\\Addins\\<year>\\SmartCon.addin manually]");
                return;
            }

            var appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            var subfolder = SmartConAddinManifest.GetInstallSubfolder(year);
            var assemblyPath = Path.Combine(appData, "SmartCon", subfolder, SmartConAddinManifest.EntryAssemblyFileName);
            var expected = SmartConAddinManifest.Build(assemblyPath, year >= SmartConAddinManifest.FirstNativeIsolationRevitYear);

            var manifestDir = Path.Combine(appData, "Autodesk", "Revit", "Addins", year.ToString());
            var manifestPath = Path.Combine(manifestDir, "SmartCon.addin");

            if (File.Exists(manifestPath)
                && string.Equals(Normalize(File.ReadAllText(manifestPath)), Normalize(expected), StringComparison.Ordinal))
            {
                SmartConLogger.Debug(".addin manifest is up to date");
                return;
            }

            Directory.CreateDirectory(manifestDir);
            var tmpPath = manifestPath + ".tmp";
            File.WriteAllText(tmpPath, expected);
            File.Copy(tmpPath, manifestPath, overwrite: true);
            File.Delete(tmpPath);

            SmartConLogger.Info(
                $".addin manifest healed for Revit {year} " +
                $"(nativeIsolation={(year >= SmartConAddinManifest.FirstNativeIsolationRevitYear ? "on" : "n/a")}, " +
                $"assembly='{assemblyPath}')");
        }
        catch (Exception ex)
        {
            SmartConLogger.Warn(
                $"AddinManifestHealer failed: {ex.GetType().Name}: {ex.Message} " +
                "[Action: reinstall SmartCon via setup.exe to restore the .addin manifest]");
        }
    }
}
